document.write('1. Declaracion de variables: ');
let nombre = "James Brown is dead!";
let edad = 99;
document.write(`nombre: ${nombre} edad: ${edad} <br/>`);
document.write('2. Tipos de datos:');
var esEstudiante = false;
var altura = 177;
document.write(`esEstudiante de tipo ${typeof(esEstudiante)} y valor: ${esEstudiante} altura de tipo ${typeof(altura)} y valor: ${altura} <br/>`);
document.write('3. Constantes: ');
const pi = 3.1459;
try{pi+=1;}catch(e){
    document.write(`Error al intentar incrementar constante pi: ${e.message} <br/>`);
}
document.write(`Pi: ${pi} <br/>`);
document.write('4. Operaciones Aritméticas: ');
let num1 = 2;
let num2 = 3;
document.write(`variables num1: ${num1} , num2: ${num2} <br/>`);
document.write(`Operaciones num1+num2: ${num1+num2} operacion num1-num2: ${num1-num2} `);
document.write(`Operaciones num1*num2: ${num1*num2} operacion num1/num2: ${num1/num2} `);
document.write(`Operaciones num1%num2: ${num1%num2} <br/>`);
document.write('5. Operadores de Asignación: ');
let x = 10;
document.write(`valor inicial de x: ${x} <br/>`);
x += 2;
document.write(`valor de x despues de +=2 : ${x} &nbsp;&nbsp;`);
x -= 2;
document.write(`valor de x despues de -=2 : ${x} &nbsp;&nbsp;`);
x *= 2;
document.write(`valor de x despues de *=2 : ${x} &nbsp;&nbsp;`);
x /= 2;
document.write(`valor de x despues de /=2 : ${x} &nbsp;&nbsp;`);
x %= 2;
document.write(`valor de x despues de %=2 : ${x} &nbsp;&nbsp; <br/>`);
document.write('6. Incremento y decremento ');
let contador = 0;
document.write(`contador original: ${contador} &nbsp;&nbsp;`);
contador++;
document.write(`contador++ : ${contador} &nbsp;&nbsp;`);
contador--;
document.write(`contador-- : ${contador} <br/>`);
alert(`6. alert1 \n valor de contador despues de incremento y decremento: ${contador} `);
document.write('7. Operadores de comparación alert2 <br/>');
let a = true, b=false;
alert(`7. alert2 \n valores de variables \n a: ${a} \n b: ${b} \n valores Operadores comparación\n a>b: ${a>b} \n a<b: ${a<b} \n a<=b : ${a<=b} \n a>=b : ${a>=b} \n a==b: ${a==b} \n a===b: ${a==+b} `);
let x2=true, y2 = true,z2= false;
document.write(`8. Operadores lógicos alerts3-5 \n valor de variables x2: ${x2} &nbsp;&nbsp; y2: ${y2} &nbsp;,&nbsp; z2: ${z2} <br/>`);
alert(`alert3 8. Operadores lógicos \n '!' negación !x2:  ${!x2}  !y2: ${!y2} ,  !z2: ${!z2} \n`);
alert(`alert4 8. resultado operadores logicos '&&': \n x2 && y2: ${x2&&y2} \n y2 && z2: ${y2&&z2} \n '(x2 && y2 && z2):' ${x2&&y2&&z2}`); 
alert(`alert5 8. resultado operadores logicos '||': \n x2 || y2: ${x2||y2} \n y2 || z2: ${y2||z2} \n '(x2 || y2 || z2):' ${x2||y2||z2} <br/>`); 
nombre = "John";
let apellido="Ramos";
document.write(`9.Concatenación de Strings, valores: nombre: ${nombre} , apellido: ${apellido} alert6 <br/>`);
alert(`alert6 9.Concatenación de Strings Nombre+Apellido: ${nombre+' '+apellido}`);
document.write('10. Conversión Tipos de datos: alert7 <br/>');
let numero=23.5;
alert(`alert7 10. Valor funcion toString() sobre variable numerica numero: ${numero.toString()} `);
document.write('11. Conversión de unidades: Km -> mts, cm, mil... alert8 <br/>');
let distanciaKm = 488;
alert(`alert8 11.Conversion de unidades: \n Distancia en km: ${distanciaKm} \n Distancia en Mts: ${distanciaKm*1000} \n Distancia en Cmts: ${distanciaKm*100000} \n Distancia en millas Mil: ${distanciaKm*1.609}`); 
document.write('12. Cálculo de Área y perímetro: alert9 <br/>');
let base=5, altura2=13.6;
let hipot = Math.sqrt(Math.pow(base,2)+Math.pow(altura2,2));
alert(`alert9 12.Perímetro y área. variables base: ${base} , altura: ${altura2} , hipotenusa: ${hipot} \n Perimetro triangulo: ${base+altura2+hipot} \n Área: ${(base*altura2)/2}`);
let calificacion1=7.5, calificacion2=6.7, calificacion3=8.0;
document.write(`13. Promedio de calificaciones: calificacion1: ${calificacion1} , calificacion2: ${calificacion2} , calificacion3: ${calificacion3} alert10 <br/>`);
alert(`alert10 13.Promedio de calificaciones: \n calificacion1: ${calificacion1} , calificacion2: ${calificacion2} , calificacion3: ${calificacion3} \n Promedio: ${(calificacion1+calificacion2+calificacion3)/3}`);
document.write('14.Descuento y precio final alert11 <br/>');
let precioInicial=857000, descuento=precioInicial*0.15, precioFinal=precioInicial*0.85;
alert(`alert11 14.Descuento y precio final \n precioInicial: ${precioInicial} \n descuento(15%): ${descuento} \n precioFinal: ${precioFinal} `);
document.write('15. Conversión de moneda alert12 <br/> ');
let quantityInUsDollars=5600;
let tasaEuroHoy = 1.08;
let tasaLbEsterlinaHoy=1.28;
let tasaYenHoy=0.0062;
alert(`alert12 15. cantidad actual en dolares: ${quantityInUsDollars} \n Cantidad en Euros: ${quantityInUsDollars*tasaEuroHoy} \n Cantidad en Libras: ${quantityInUsDollars*tasaLbEsterlinaHoy} \n cantidad en Yenes: ${quantityInUsDollars*tasaYenHoy} \n Fin.`);